// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyCw2sETnS4JH0Bq5nrciPpBmckNj9-Ul0o",
  authDomain: "idx-8b7b5.firebaseapp.com",
  projectId: "idx-8b7b5",
  storageBucket: "idx-8b7b5.appspot.com",
  messagingSenderId: "1059709621665",
  appId: "1:1059709621665:web:aeadaae6e7836b1b3a27e0",
  measurementId: "G-MGT8ZEGKRX"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCw2sETnS4JH0Bq5nrciPpBmckNj9-Ul0o",
  authDomain: "idx-8b7b5.firebaseapp.com",
  projectId: "idx-8b7b5",
  storageBucket: "idx-8b7b5.appspot.com",
  messagingSenderId: "1059709621665",
  appId: "1:1059709621665:web:aeadaae6e7836b1b3a27e0",
  measurementId: "G-MGT8ZEGKRX"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCw2sETnS4JH0Bq5nrciPpBmckNj9-Ul0o",
  authDomain: "idx-8b7b5.firebaseapp.com",
  projectId: "idx-8b7b5",
  storageBucket: "idx-8b7b5.appspot.com",
  messagingSenderId: "1059709621665",
  appId: "1:1059709621665:web:aeadaae6e7836b1b3a27e0",
  measurementId: "G-MGT8ZEGKRX"
  );

  static const FirebaseOptions macos = FirebaseOptions(
   apiKey: "AIzaSyCw2sETnS4JH0Bq5nrciPpBmckNj9-Ul0o",
  authDomain: "idx-8b7b5.firebaseapp.com",
  projectId: "idx-8b7b5",
  storageBucket: "idx-8b7b5.appspot.com",
  messagingSenderId: "1059709621665",
  appId: "1:1059709621665:web:aeadaae6e7836b1b3a27e0",
  measurementId: "G-MGT8ZEGKRX"
  );
}